### ISSUE TITLE
"Degree" parameters invalid?

### ISSUE THREAD

**Issue by justintconroy** [tapnair/ParamEdit#5]
I get a popup when I open the ParamEdit dialog for all of my paramters with units of degree

![image](https://user-images.githubusercontent.com/214411/85072533-e25d9180-b17e-11ea-8d01-a620f4b50dfd.png)

It's rather annoying.

**Comment by tapnair** [comment]
hmmm not sure.  It must be doing something wrong with the degree units.  But this app isn't really that useful anymore since the thing it did is implemented in Fusion.  Curious what you are using it for?

**Comment by justintconroy** [comment]
I guess I didn't realize it was filling that niche before. I'm rather new to Fusion. Really, I just tried it out to see if it would be a less annoying interface for parameters. 😸
